spring:
    application:
        name: estudo-de-caso-v2
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy 
        database: POSTGRESQL
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
            hibernate.temp.use_jdbc_metadata_defaults: false
    datasource:
        url: jdbc:postgresql://localhost:5432/abim
        username: abim
        password: abim
server:
    port: 8090
logging:
    level:
        ROOT: ERROR
        br.com.abim.ec: DEBUG
